Don't log full error
polkadot-js/api pull request #2952
Opened 2020-12-14 14:37 UTC by dvdplm

In `txwrapper` we can't always know if a payload is a signing payload or a signed tx so we first try one and then the other. When the former fails users get a scary-looking error. If upstream logs the error there's little we can do about it lest we [monkey patch `console.error`](https://github.com/paritytech/txwrapper-core/pull/22/files#diff-ea2d1c5845dd0e2fb9814e98a3464c2c63a43922983391e98fe9c20c328e979cR55) which is nasty af.

Hence this PR that removes the log here so that downstream can choose what to do with the error message.

rel. https://github.com/paritytech/txwrapper-core/issues/20

2020-12-14 15:00 UTC, jacogr commented
Not quite convinced. Have been trying to remove the logging in all the specific codec parts and only rely on this as a single point of all type-decoding logs. As examples - Call used to have specific logging on failures, as did Struct, etc. 

Will have to see what the impact is.

2020-12-14 16:36 UTC, jacogr commented
This will work and solve the need,

`createTypeUnsafe<T extends Codec = Codec, K extends string = string> (registry: Registry, type: K, params: any[] = [], isPedantic?: boolean): T`

changes to

`createTypeUnsafe<T extends Codec = Codec, K extends string = string> (registry: Registry, type: K, params: any[] = [], { isPedantic, withoutLog }: UnsafeOptions = {}): T`

Obviously the `l.error` line becomes `!withoutLog && l.error(...)`

Then call `createTypeUnsafe` directly, the only difference is really the params compared to `createType`, it is passed as an explicit array.

Would be happy with an adjustment like that that solves the need, without breaking the existing behavior.

2020-12-15 09:26 UTC, jacogr requested changes
As suggested, not quite convinced as-is, but if the commented changes are applied, would be good since it -

- will allow the specific raised issue to be addressed
- not change the API logging to have nothing (since it is localised in the single place now ... well, there are some places left which has not been caught, Rome was not built in a day)

2020-12-15 10:07 UTC, dvdplm commented
Cool, thank you. Will proceed as indicated.

2020-12-16 10:21 UTC, jacogr reviewed
Thank you, looks great and hopefully solves your issue.

Some small comments just to not pass through the `withoutLog` each time. Otherwise, does what is says on the tin.

2020-12-16 10:21 UTC, jacogr commented on packages/api-contract/src/util.ts
> +  return createTypeUnsafe(registry, type, [data], { isPedantic: true, withoutLog: false });
```suggestion
  return createTypeUnsafe(registry, type, [data], { isPedantic: true });
```

2020-12-16 10:21 UTC, jacogr commented on packages/rpc-core/src/index.ts
> +          inner = createTypeUnsafe(registry, type, [input], { isPedantic: true, withoutLog: false });
```suggestion
          inner = createTypeUnsafe(registry, type, [input], { isPedantic: true });
```

2020-12-16 10:21 UTC, jacogr commented on packages/rpc-core/src/index.ts
> +      ], { isPedantic: true, withoutLog: false });
```suggestion
      ], { isPedantic: true });
```

2020-12-16 10:21 UTC, jacogr commented on packages/types/src/create/createType.ts
> +export function createTypeUnsafe<T extends Codec = Codec, K extends string = string> (registry: Registry, type: K, params: any[] = [], { isPedantic, withoutLog }: UnsafeOptions = { }): T {
```suggestion
export function createTypeUnsafe<T extends Codec = Codec, K extends string = string> (registry: Registry, type: K, params: any[] = [], { isPedantic, withoutLog }: UnsafeOptions = {}): T {
```

2020-12-16 12:12 UTC, jacogr approved these changes
Brilliant, thank you.

2020-12-16 12:12 UTC, merged