Adds tests cases for issue #5702
polkadot-js/api pull request #5703
Opened 2023-08-17 11:27 UTC by peetzweg

See #5702 for further details.

2023-08-17 13:22 UTC, jacogr requested changes
Always appreciate this. Obviously it cannot be merged but useful for somebody that wishes to look into the logged issue - if CI fails the PR is not merge-able, but somebody can certainly copy this/parts of it into their effort.

One comment:

If anything fails you need to delve through an it statement to find the place - so each `it` should have 1 expectation (maybe more, if they are very closely related and follow-ups of each other and easy to find)

In some cases it is possible, in others it would be impossible to find which one creates issues, for instance

```js
// Zero
    expect(
      new Int(registry, new Uint8Array([0]), 8).toNumber()
    ).toEqual(0);

    expect(
      new Int(registry, new Uint8Array([0, 0]), 16).toNumber()
    ).toEqual(0);
```

TL;DR Rather use a `describe` block with specific `it` + (one) `expect` for each.

2023-08-17 13:57 UTC, peetzweg commented
Thanks @jacogr for pointing out where these errors might root from. Tried looking into it a bit already, will continue from there.

> In some cases it is possible, in others it would be impossible to find which one creates issues, for instance

Yes, agree it's not as transparent which one failed, however the stacktrace reveals which one it actually failed i.e.
```
  at TestContext.<anonymous> (/Users/xxx/git/pjs-api/packages/types-codec/src/base/Int.spec.ts:113:7)
``` 
  
Copy pasting almost identical `it`s is quite cumbersome. Unfortunately we can't create [parameterized tests](https://vitest.dev/api/#test-each) with @polkadot/dev-test right?

There also seems to be an issue with decoding just the value `0` to a Number, which results in 
```
i8: Input too large. Found input with 9 bits, expected 8
```
https://github.com/peetzweg/api/blob/f33bbc8340d66f46b77da041bfc1467b3d33c450/packages/types-codec/src/base/Int.spec.ts#L111-L114

Which is a quite odd. 🤔

2023-08-25 10:23 UTC, jacogr commented
Could you merge in the master branch (it contains the latest common stuff). Hopefully it means the test cases here would start passing…

2023-08-25 10:52 UTC, peetzweg commented
@jacogr done! They succeed locally now. Great job! 🙌

2023-08-29 09:34 UTC, jacogr submitted a review, later dismissed

2023-08-29 10:01 UTC, jacogr commented on packages/types-codec/src/base/Int.spec.ts
> +
```suggestion
```

2023-08-29 10:01 UTC, jacogr commented on packages/types-codec/src/base/Int.spec.ts
> +
```suggestion
```

2023-08-29 10:10 UTC, jacogr approved these changes
Thank you.

2023-08-29 10:10 UTC, merged