fix: ChargeAssetTxPayment to work with Asset Conversion on Westend's and Kusama's Asset Hubs
polkadot-js/api pull request #5752
Opened 2023-11-14 22:17 UTC by bee344

Since the addition of the new `pallet-asset-conversion` to `Kusama Asset Hub` and `Westend Asset Hub`, the `ChargeAssetTxPayment` mutated to accept a `MultiLocation` as the ID of the asset used to pay the tx fees, which in turn broke the decoding of the blocks in which it was present. What this PR does is fix that by modifying the signed extension for the cases of KAH and WAH, by integrating an alias that modifies the SE to use `AssetId` or `MultiLocation` depending on the runtime version. At the same time, as the introduction of the pallet was at different times on KAH and WAH and was not added in Polkadot Asset Hub, it adds `type` override files for each of them, and leaves the `statemint` one without change.
It also modifies `SignerOptions` to accept an `object` for the SE `assetId`, so that a `MultiLocation` can be passed and the SE be used in a straightforward manner.

Closes [Issue 5750](https://github.com/polkadot-js/api/issues/5750#) and [5734](https://github.com/polkadot-js/api/issues/5734) (probably).

2023-11-14 22:24 UTC, TarikGul commented
I can confirm this fixes the decoding issue we've been seeing with the assetId being as a multilocation.

2023-11-15 11:01 UTC, jacogr approved these changes
Seems sane, thank you.

2023-11-15 13:37 UTC, jacogr requested changes
Some small nigglies identified by CI, see https://github.com/polkadot-js/api/actions/runs/6870177012/job/18703510196?pr=5752#step:5:1294

It basically just needs a default type definition for the added type - generally we probably want to point this to the latest definition, which also means that the higher-version specs don't need the override.

So basically -

1. add a default to point to `Option<MultiLocation>`
2. keep the override for lower versions (as required)
3. remove the override for current versions (meaning we don't need to keep adding them into the future)

2023-11-15 17:58 UTC, bee344 commented
@jacogr I added the default types as you suggested and it solved the issues, but I also had to modify the Signer test to account for the assetId being a MultiLocation

2023-11-15 18:13 UTC, jacogr commented
@bee344 All good, I appreciate your persistence :)

2023-11-16 07:26 UTC, jacogr approved these changes

2023-11-16 07:26 UTC, merged