fix: add lookupTypes to typegen imports
polkadot-js/api pull request #5769
Opened 2023-12-10 13:59 UTC by Muhammad-Altabba

## Description

Fixes: #5765

The `lookupTypes` are missed from the list used to extract imports for the generated types. 
This MR will add it back.

2023-12-17 18:00 UTC, Muhammad-Altabba commented
The MR also resolves: https://github.com/polkadot-js/docs/issues/252

2023-12-18 07:20 UTC, jacogr requested changes
The build fails because of this. On the top-level imports it now tries to include the lookup types from `@polkadot/types` since it was added to the top-level definition.

https://github.com/polkadot-js/api/actions/runs/7158255406/job/19733755190?pr=5769

It has these dupes since in the next section we explicitly import from lookup on line 52.

2023-12-18 07:42 UTC, Muhammad-Altabba commented
> The build fails because of this. On the top-level imports it now tries to include the lookup types from `@polkadot/types` since it was added to the top-level definition.
> 
> https://github.com/polkadot-js/api/actions/runs/7158255406/job/19733755190?pr=5769
> 
> It has these dupes since in the next section we explicitly import from lookup on line 52.

So what is your suggestion to fix the issue?

And did you try to generate the files locally and saw that there are missed imports for lookups? Or you where able to generate with no issues?

Thanks,

2023-12-19 09:46 UTC, jacogr commented
CI generates code for - Substrate, Kusama and Polkadot on each build. So it gets used each time there is a PR and each time there is a build - it literally runs as part of the API build process.

2025-02-14 12:19 UTC, closed without merging

2025-02-14 12:19 UTC, valentinfernandez1 commented
Closing outdated PR